version: '3.9'

services:
  vania:
    build: .
    image: vania/app:latest
    container_name: vania
    restart: unless-stopped
    volumes:
      - app:/app
      - ./public:/public
      - ./storage:/storage
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: vania_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=vania
      - POSTGRES_PASSWORD=vania
      - POSTGRES_DB=vania
    ports:
      - '5432:5432'
    volumes:
      - vania-db:/var/lib/postgresql/data

volumes:
  app:
  vania-db:
    name: vania-db
